version: '2.7'
services:
  service1:
    build: ./service1
    networks:
      serwisy_services-network:
        ipv4_address: 172.20.1.1
    ports:
      - "5001:5000"

  service2:
    build: ./service2
    networks:
      serwisy_services-network:
        ipv4_address: 172.20.1.2
    ports:
      - "5002:5000"

  service3:
    build: ./service3
    networks:
      serwisy_services-network:
        ipv4_address: 172.20.1.3
    ports:
      - "5003:5000"

networks:
  serwisy_services-network:
    external: true